baseURL = "https://toppers.github.io/hakoniwa"
languageCode = "ja"
title = "箱庭"
theme = "kube"
description = "IoT／クラウドロボティクス時代の仮想シミュレーション環境"
Paginate = 4
googleAnalytics = "UA-169187702-1"

DefaultContentLanguage = "ja"

[languages]
  [languages.ja]
    languageName = "JP"
    weight = 1
  [languages.en]
    languageName = "EN"
    title = "Hakoniwa"
    contentDir = 'content/en'
    weight = 2
    [languages.en.menu]
[[languages.en.menu.main]]
    name = "What's Hakoniwa"
    weight = -100
    url = "/en/docs/"
[[languages.en.menu.main]]
    name = "Prototype models"
    weight = -90
    url = "/en/prototypes/"
[[languages.en.menu.main]]
    name = "Repository"
    weight = -70
    url = "/en/repositories/"
[[languages.en.menu.main]]
    name = "Contact us"
    weight = -10
    url = "/en/contact/"

[Params]
  RSSLink = "/index.xml"
  author = "TOPPERS Project Hakoniwa WG" # add your company name
  email = "secretariat@toppers.jp"
  twitter = "@toppersjp" # add your twitter pro
  images = ["img/hakoniwa/icon-310x310.png"]
  facebookAppId = "3035581286538848"

[[menu.main]]
    name = "箱庭とは"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "プロトタイプモデル"
    weight = -90
    url = "/prototypes/"
[[menu.main]]
    name = "技術情報"
    weight = -80
    url = "/technical-links/"
[[menu.main]]
    name = "ショーケース"
    weight = -75
    url = "/showcase/"
[[menu.main]]
    name = "Getting Started"
    weight = -70
    url = "/getting-started/"
[[menu.main]]
    name = "リポジトリ"
    weight = -60
    url = "/repositories/"
[[menu.main]]
    name = "SNS・問合せ先"
    weight = -10
    url = "/contact/"
