baseURL = "https://toppers.github.io/hakoniwa/"
languageCode = "ja"
title = "Top"
theme = "kube"
description = "IoT／自動運転時代の仮想シミュレーション環境"
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "TOPPERS Project HAKONIWA WG" # add your company name
  email = "secretariat@toppers.jp"

[[menu.main]]
    name = "箱庭とは"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "プロトタイプモデル"
    weight = -90
    url = "/prototypes/"
[[menu.main]]
    name = "技術情報・発表資料"
    weight = -80
    url = "/technical-links/"
[[menu.main]]
    name = "問合せ先"
    weight = -70
    url = "/contact/"
