baseURL = "https://toppers.github.io/hakoniwa/"
languageCode = "ja"
title = "箱庭"
theme = "kube"
description = "IoT／自動運転時代の仮想シミュレーション環境"
Paginate = 4
googleAnalytics = "UA-169187702-1"

[Params]
  RSSLink = "/index.xml"
  author = "TOPPERS Project HAKONIWA WG" # add your company name
  email = "secretariat@toppers.jp"
  twitter = "@toppersjp" # add your twitter pro
  images = ["img/hakoniwa/icon-310x310.png"]
  facebookAppId = "3035581286538848"

[[menu.main]]
    name = "箱庭とは"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "プロトタイプモデル"
    weight = -90
    url = "/prototypes/"
[[menu.main]]
    name = "技術情報"
    weight = -80
    url = "/technical-links/"
[[menu.main]]
    name = "ショーケース"
    weight = -75
    url = "/showcase/"
[[menu.main]]
    name = "リポジトリ"
    weight = -70
    url = "/repositories/"
[[menu.main]]
    name = "SNS・問合せ先"
    weight = -10
    url = "/contact/"
